### ISSUE TITLE
Part of Japanese man lacks

### ISSUE THREAD

**Issue by fu-sen** [gapan/gtkman#3]
The Slint project members and I were promoting the adoption of Japanese man for Slint.
As one of them, I attempted to display Japanese man with GTKMan.
However, some of them are missing.

(The display below is indicated by Salix)
[![_2016-12-06_11-39-19.md.jpg](https://cdn.scrot.moe/images/2016/12/06/_2016-12-06_11-39-19.md.jpg)](https://scrot.moe/image/FSU0)

Normal display of that man:
[![slint-man-konqueror.md.jpg](https://cdn.scrot.moe/images/2016/12/06/slint-man-konqueror.md.jpg)](https://scrot.moe/image/Ff6A)

Probably GTKMan seems to be malfunctioning with multibyte code processing tags around.

I confirm this setting: https://github.com/gapan/gtkman/issues/2

In order to display Japanese manual correctly, "man" command is replaced with "man-db".

**Comment by gapan** [comment]
No. You're looking at different manpages. They both have the same name, but they are different, the contents are different. If you use gtkman on the same system from where that second manpage was taken from, it will display the same contents.
