### ISSUE TITLE
DEPRECATION: Python 2.x

### ISSUE THREAD

**Issue by dodona2** [gapan/gtkman#5]
Fedora31 users install python2; replace python by python2 at line 1 of gtkman.
However this will 'fix' the problem only temporarily, as:

'DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.'

**Comment by gapan** [comment]
It seems I had forgotten to update this for Python3 and GTK+3. I just tagged version 2.0 which upgrades both. Thanks for the reminder!
