### ISSUE TITLE
package problems

### ISSUE THREAD

**Issue by dodona2** [gapan/gtkman#6]
**-> invoking gtkman after the most recent update:**
 
gtkman 
Traceback (most recent call last):
  File "/usr/local/bin/gtkman", line 13, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**--> changing import ConfigParser to import  configparser:**

(2/1)~$ gtkman 
/usr/local/bin/gtkman:18: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
Traceback (most recent call last):
  File "/usr/local/bin/gtkman", line 48, in <module>
    class GTKMan:
  File "/usr/local/bin/gtkman", line 49, in GTKMan
    config = ConfigParser.RawConfigParser()
NameError: name 'ConfigParser' is not defined

**--> sed'ing all occurences of ConfigParser to configparser:**

(2/1)~$ gtkman 
/usr/local/bin/gtkman:18: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
Traceback (most recent call last):
  File "/usr/local/bin/gtkman", line 48, in <module>
    class GTKMan:
  File "/usr/local/bin/gtkman", line 49, in GTKMan
    config = configparser.Rawconfigparser()
AttributeError: module 'configparser' has no attribute 'Rawconfigparser'

**Comment by gapan** [comment]
I don't think you have the latest commit. Can you make sure you pull from master?

**Comment by dodona2** [comment]
did one at 00:06h CET, which fails, The most receent (~5 minutes ago) is working. Got that warnings:
gtkman 
/usr/local/bin/gtkman:16: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/local/bin/gtkman:577: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  self.textview_manpage.modify_font(Pango.FontDescription('monospace'))

**Comment by dodona2** [comment]
thanks a lot [George](https://github.com/gapan)(gapan).

**Comment by gapan** [comment]
I'm not getting those warnings here, but I probably have an old GTK+3 version installed. What version do you get those with? I'm guessing it works OK for you despite the warnings?

**Comment by dodona2** [comment]
Python 3.7.5
