### ISSUE TITLE
V2.0:  Minor depreciation warnings

### ISSUE THREAD

**Issue by mlmatlock** [gapan/gtkman#7]
When opening gtkman:
<pre><code>
/usr/bin/gtkman:16: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/bin/gtkman:577: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  self.textview_manpage.modify_font(Pango.FontDescription('monospace'))
</code></pre>
When clicking on the 'index' button:
<pre><code>
/usr/bin/gtkman:415: DeprecationWarning: Gdk.threads_enter is deprecated
  Gdk.threads_enter()
/usr/bin/gtkman:417: DeprecationWarning: Gdk.threads_leave is deprecated
  Gdk.threads_leave()
</code></pre>
Other than that, looking good!

**Comment by gapan** [comment]
What GTK+3 version are you running? I don't see those, but I probably have an old GTK+3.

**Comment by dodona2** [comment]
**I can confirm that for fedora 31!**

**gtk3 version**: gtk3(x86-64) = 3.24.12-3.fc31/3.24.12-3.fc31

_$ gtkman
/usr/local/bin/gtkman:16: DeprecationWarning: Gdk.threads_init is deprecated
  Gdk.threads_init()
/usr/local/bin/gtkman:577: DeprecationWarning: Gtk.Widget.modify_font is deprecated
  self.textview_manpage.modify_font(Pango.FontDescription('monospace'))_

**Comment by gapan** [comment]
OK, thanks! I'll need to install a newer GTK, so it might take a while... Since everything is working I guess that's OK.

**Comment by mlmatlock** [comment]
@gapan:

Arch, gtk3 v3.24.13

**Comment by mlmatlock** [comment]
@gapan,

Looks good!  Thanks!
